[package]
name = "render"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.27.0"
nalgebra = "0.33.2"
ndarray = "0.16.1"
num_cpus = "1.16.0"
rayon = "1.10.0"
vulkano = "0.34.1"
vulkano-shaders = "0.34.0"
bytemuck = "1.21.0"
